In [1]:
from transformers import pipeline

In [2]:
classifier=pipeline("sentiment-analysis",model="")

No model was supplied, defaulted to distilbert-base-uncased-finetuned-sst-2-english and revision af0f99b (https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.
All PyTorch model weights were used when initializing TFDistilBertForSequenceClassification.

All the weights of TFDistilBertForSequenceClassification were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFDistilBertForSequenceClassification for predictions without further training.


In [3]:
classifier("you look nice")

[{'label': 'POSITIVE', 'score': 0.9998452663421631}]

In [14]:

from transformers  import AutoTokenizer

In [5]:
checkpoint='distilbert-base-uncased-finetuned-sst-2-english'
tokenizer=AutoTokenizer.from_pretrained(checkpoint)

In [18]:
raw_inputs=[
    "I love hugging face and belive in them",
    "I hate my college"
]
inputs=tokenizer(raw_inputs,padding=True,truncation=True,return_tensors='tf')
print(inputs)

{'input_ids': <tf.Tensor: shape=(2, 11), dtype=int32, numpy=
array([[  101,  1045,  2293, 17662,  2227,  1998, 19337,  3512,  1999,
         2068,   102],
       [  101,  1045,  5223,  2026,  2267,   102,     0,     0,     0,
            0,     0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(2, 11), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0]], dtype=int32)>}


In [19]:
from transformers import TFAutoModel
checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
model=TFAutoModel.from_pretrained(checkpoint)

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFDistilBertModel: ['classifier.weight', 'pre_classifier.weight', 'pre_classifier.bias', 'classifier.bias']
- This IS expected if you are initializing TFDistilBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFDistilBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFDistilBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFDistilBertModel for predictions without further training.


In [20]:
output=model(inputs)
print(output.last_hidden_state.shape)

(2, 11, 768)


In [21]:
from transformers import TFAutoModelForSequenceClassification

checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
model = TFAutoModelForSequenceClassification.from_pretrained(checkpoint)
outputs = model(inputs)

All PyTorch model weights were used when initializing TFDistilBertForSequenceClassification.

All the weights of TFDistilBertForSequenceClassification were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFDistilBertForSequenceClassification for predictions without further training.


In [27]:
#print(outputs.logits.shape)
#type(outputs.logits)
print(outputs.logits)


(2, 2)
tf.Tensor(
[[-4.2064223  4.545987 ]
 [ 4.3391185 -3.5261562]], shape=(2, 2), dtype=float32)


In [28]:
import tensorflow as tf

In [29]:
pred=tf.math.softmax(outputs.logits,axis=-1)
print(pred)

tf.Tensor(
[[1.5805507e-04 9.9984193e-01]
 [9.9961627e-01 3.8369669e-04]], shape=(2, 2), dtype=float32)


In [30]:
model.config.id2label


{0: 'NEGATIVE', 1: 'POSITIVE'}