In [13]:
from datasets import load_dataset

issues_data=load_dataset("lewtun/github-issues",split="train")

Repo card metadata block was not found. Setting CardData to empty.


In [14]:
issues_data.shape

(3019, 28)

In [15]:
issues_data["is_pull_request"]

[True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 True,
 False,
 True,
 True,
 True,
 False,
 True,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 True,
 False,
 True,
 True,
 False,
 False,
 False,
 True,
 False,
 True,
 True,
 True,
 False,
 True,
 False,
 False,
 True,
 False,
 True,
 True,
 True,
 False,
 True,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 True,
 False,
 True,
 True,
 True,
 False,
 True,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 True,
 

In [16]:
issues_data=issues_data.filter(lambda x:x["is_pull_request"]==False and len(x["comments"])>0)

In [17]:
issues_data

Dataset({
    features: ['url', 'repository_url', 'labels_url', 'comments_url', 'events_url', 'html_url', 'id', 'node_id', 'number', 'title', 'user', 'labels', 'state', 'locked', 'assignee', 'assignees', 'milestone', 'comments', 'created_at', 'updated_at', 'closed_at', 'author_association', 'active_lock_reason', 'pull_request', 'body', 'timeline_url', 'performed_via_github_app', 'is_pull_request'],
    num_rows: 808
})

In [18]:
col=issues_data.column_names
col_keep=["title", "body", "html_url", "comments"]
col_rem=set(col_keep).symmetric_difference(col)
issues_data=issues_data.remove_columns(col_rem)
issues_data

Dataset({
    features: ['html_url', 'title', 'comments', 'body'],
    num_rows: 808
})

In [19]:
issues_data.set_format("pandas")
df=issues_data[:]

In [20]:
df

html_url  \
0    https://github.com/huggingface/datasets/issues...   
1    https://github.com/huggingface/datasets/issues...   
2    https://github.com/huggingface/datasets/issues...   
3    https://github.com/huggingface/datasets/issues...   
4    https://github.com/huggingface/datasets/issues...   
..                                                 ...   
803   https://github.com/huggingface/datasets/issues/6   
804   https://github.com/huggingface/datasets/issues/5   
805   https://github.com/huggingface/datasets/issues/4   
806   https://github.com/huggingface/datasets/issues/3   
807   https://github.com/huggingface/datasets/issues/2   

                                                 title  \
0                                Protect master branch   
1    Backwards compatibility broken for cached data...   
2    OSCAR unshuffled_original_ko: NonMatchingSplit...   
3    load_dataset using default cache on Windows ca...   
4    to_tf_dataset keeps a reference to the open da...   
..                                                 ...   
803  Error when citation is not given in the Datase...   
804                   ValueError when a split is empty   
805  [Feature] Keep the list of labels of a dataset...   
806                     [Feature] More dataset outputs   
807                      Issue to read a local dataset   

                                              comments  \
0    [Cool, I think we can do both :), @lhoestq now...   
1    [Hi ! I guess the caching mechanism should hav...   
2    [I tried `unshuffled_original_da` and it is al...   
3    [Hi @daqieq, thanks for reporting.\r\n\r\nUnfo...   
4    [I did some investigation and, as it seems, th...   
..                                                 ...   
803  [Yes looks good to me.\r\nNote that we may ref...   
804  [To fix this I propose to modify only the file...   
805  [Yes! I see mostly two options for this:\r\n- ...   
806  [Yes!\r\n- pandas will be a one-liner in `arro...   
807  [My first bug report ❤️\r\nLooking into this r...   

                                                  body  
0    After accidental merge commit (91c55355b634d0d...  
1    ## Describe the bug\r\nAfter upgrading to data...  
2    ## Describe the bug\r\n\r\nCannot download OSC...  
3    ## Describe the bug\r\nStandard process to dow...  
4    To reproduce:\r\n```python\r\nimport datasets ...  
..                                                 ...  
803  The following error is raised when the `citati...  
804  When a split is empty either TEST, VALIDATION ...  
805  It would be useful to keep the list of the lab...  
806  Add the following dataset outputs:\r\n\r\n- Sp...  
807  Hello,\r\n\r\nAs proposed by @thomwolf, I open...  

[808 rows x 4 columns]

In [21]:
df["comments"][0].tolist()

['Cool, I think we can do both :)',
 '@lhoestq now the 2 are implemented.\r\n\r\nPlease note that for the the second protection, finally I have chosen to protect the master branch only from **merge commits** (see update comment above), so no need to disable/re-enable the protection on each release (direct commits, different from merge commits, can be pushed to the remote master branch; and eventually reverted without messing up the repo history).']

In [22]:
comments_df=df.explode("comments",ignore_index=True)
comments_df.head()

html_url  \
0  https://github.com/huggingface/datasets/issues...   
1  https://github.com/huggingface/datasets/issues...   
2  https://github.com/huggingface/datasets/issues...   
3  https://github.com/huggingface/datasets/issues...   
4  https://github.com/huggingface/datasets/issues...   

                                               title  \
0                              Protect master branch   
1                              Protect master branch   
2  Backwards compatibility broken for cached data...   
3  Backwards compatibility broken for cached data...   
4  Backwards compatibility broken for cached data...   

                                            comments  \
0                    Cool, I think we can do both :)   
1  @lhoestq now the 2 are implemented.\r\n\r\nPle...   
2  Hi ! I guess the caching mechanism should have...   
3  If it's easy enough to implement, then yes ple...   
4  Well it can cause issue with anyone that updat...   

                                                body  
0  After accidental merge commit (91c55355b634d0d...  
1  After accidental merge commit (91c55355b634d0d...  
2  ## Describe the bug\r\nAfter upgrading to data...  
3  ## Describe the bug\r\nAfter upgrading to data...  
4  ## Describe the bug\r\nAfter upgrading to data...

In [23]:
from datasets import Dataset
# comments_dataset=Dataset.from_pandas(comments_df)
# comments_dataset
comments_dataset = Dataset.from_pandas(comments_df)
comments_dataset

Dataset({
    features: ['html_url', 'title', 'comments', 'body'],
    num_rows: 2964
})

In [24]:
comments_dataset=comments_dataset.map(lambda x:{"comment_length":len(x["comments"].split())})

Map:   0%|          | 0/2964 [00:00<?, ? examples/s]

In [25]:
comments_dataset=comments_dataset.filter(lambda x:x["comment_length"]>15)
comments_dataset

Filter:   0%|          | 0/2964 [00:00<?, ? examples/s]

Dataset({
    features: ['html_url', 'title', 'comments', 'body', 'comment_length'],
    num_rows: 2175
})

In [26]:
comments_dataset=comments_dataset.map(lambda x:{
    "text":x["title"]
    + "\n"
    + x["body"]
    + "\n"
    + x["comments"]
    
})

Map:   0%|          | 0/2175 [00:00<?, ? examples/s]

In [27]:
from transformers import AutoTokenizer,TFAutoModel
model_ckpt="sentence-transformers/multi-qa-mpnet-base-dot-v1"
tokenizer=AutoTokenizer.from_pretrained(model_ckpt)
model=TFAutoModel.from_pretrained(model_ckpt,from_pt=True)

2023-09-24 01:53:01.506241: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M1
2023-09-24 01:53:01.506261: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 8.00 GB
2023-09-24 01:53:01.506270: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 2.67 GB
2023-09-24 01:53:01.506893: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:303] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2023-09-24 01:53:01.507050: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:269] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)
Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFMPNetModel: ['embeddings.position_ids']
- This IS expected if you are initializing TFMPNetModel from a

In [28]:
def cls_pooling(model_output):
    return model_output.last_hidden_state[:,0]

In [29]:
encoded_input=tokenizer(comments_dataset["text"][:5],padding=True, truncation=True, return_tensors="tf")

In [30]:
encoded_input

{'input_ids': <tf.Tensor: shape=(5, 512), dtype=int32, numpy=
array([[    0,  4051,  3044, ...,     1,     1,     1],
       [    0, 11047, 21782, ...,  1016, 17057,     2],
       [    0, 11047, 21782, ...,  1016, 17057,     2],
       [    0, 11047, 21782, ...,  1016, 17057,     2],
       [    0, 11047, 21782, ...,  1016, 17057,     2]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(5, 512), dtype=int32, numpy=
array([[1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]], dtype=int32)>}

In [31]:
encoded_input = {k: v for k, v in encoded_input.items()}

In [32]:
encoded_input

{'input_ids': <tf.Tensor: shape=(5, 512), dtype=int32, numpy=
 array([[    0,  4051,  3044, ...,     1,     1,     1],
        [    0, 11047, 21782, ...,  1016, 17057,     2],
        [    0, 11047, 21782, ...,  1016, 17057,     2],
        [    0, 11047, 21782, ...,  1016, 17057,     2],
        [    0, 11047, 21782, ...,  1016, 17057,     2]], dtype=int32)>,
 'attention_mask': <tf.Tensor: shape=(5, 512), dtype=int32, numpy=
 array([[1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1]], dtype=int32)>}

In [33]:
model(**encoded_input)

TFBaseModelOutputWithPooling(last_hidden_state=<tf.Tensor: shape=(5, 512, 768), dtype=float32, numpy=
array([[[-1.55319750e-01, -1.00230552e-01, -7.03210235e-02, ...,
         -1.52763486e-01,  6.11720756e-02, -1.98785812e-01],
        [-8.91083330e-02,  1.13443509e-01, -1.67645380e-01, ...,
         -1.86630547e-01,  7.04902709e-02, -1.66866958e-01],
        [-1.29643872e-01, -1.22836448e-01, -1.30288675e-01, ...,
         -3.26714963e-01, -6.72660768e-04, -5.60678206e-02],
        ...,
        [ 6.51642084e-02, -6.04542121e-02, -1.94934785e-01, ...,
         -2.19161324e-02, -1.22386664e-01, -1.26843691e-01],
        [ 6.52385950e-02, -5.86896464e-02, -1.94787800e-01, ...,
         -2.20095664e-02, -1.22267865e-01, -1.27117902e-01],
        [ 6.58856034e-02, -5.79189733e-02, -1.94597036e-01, ...,
         -2.21509039e-02, -1.22761920e-01, -1.27215356e-01]],

       [[-3.04995358e-01,  1.24387980e-01, -4.65585105e-02, ...,
         -8.82679671e-02,  2.77353525e-01, -1.29942030e-01],
 

In [34]:
encoded_input.items()


dict_items([('input_ids', <tf.Tensor: shape=(5, 512), dtype=int32, numpy=
array([[    0,  4051,  3044, ...,     1,     1,     1],
       [    0, 11047, 21782, ...,  1016, 17057,     2],
       [    0, 11047, 21782, ...,  1016, 17057,     2],
       [    0, 11047, 21782, ...,  1016, 17057,     2],
       [    0, 11047, 21782, ...,  1016, 17057,     2]], dtype=int32)>), ('attention_mask', <tf.Tensor: shape=(5, 512), dtype=int32, numpy=
array([[1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]], dtype=int32)>)])

In [35]:
def get_embeddings(text_list):
    encoded_input=tokenizer(text_list,padding=True, truncation=True, return_tensors="tf")
    encoded_input = {k: v for k, v in encoded_input.items()}
    model_output=model(**encoded_input)
    return cls_pooling(model_output)
    

In [60]:
embedding = get_embeddings(comments_dataset["text"][0])
embedding.shape

TensorShape([1, 768])

In [ ]:
embedding_dataset=comments_dataset.map(lambda x:{"embeddings":get_embeddings(x["text"]).numpy()[0]})


Parameter 'function'=<function <lambda> at 0x2950bf880> of the transform datasets.arrow_dataset.Dataset._map_single couldn't be hashed properly, a random hash was used instead. Make sure your transforms and parameters are serializable with pickle or dill for the dataset fingerprinting and caching to work. If you reuse this transform, the caching mechanism will consider it to be different from the previous calls and recompute everything. This warning is only showed once. Subsequent hashing failures won't be showed.


Map:   0%|          | 0/2175 [00:00<?, ? examples/s]

In [1]:
print("hello world")

hello world


In [5]:
from datasets import load_dataset_builder,load_dataset

# Replace 'path/to/saved/dataset' with the path to the directory where you saved the dataset
builder = load_dataset_builder("/Users/debruppaul/Untitled Folder/transformers-course/datasets/embedings_fasis")

In [6]:
embedding_dataset=load_dataset("json",data_files="/Users/debruppaul/Downloads/data_1")

In [7]:
embedding_data=embedding_dataset["train"]

In [8]:
import faiss

In [10]:
embedding_data.add_faiss_index(column="embeddings")

  0%|          | 0/3 [00:00<?, ?it/s]

Dataset({
    features: ['html_url', 'title', 'comments', 'body', 'comment_length', 'text', 'embeddings'],
    num_rows: 2175
})

In [37]:
question = "How can I load a dataset offline?"
question_embedding = get_embeddings([question]).numpy()
question_embedding.shape

(1, 768)

In [38]:
scores,samples=embedding_data.get_nearest_examples("embeddings",question_embedding,k=5)

In [42]:
type(samples)

dict

In [39]:
import pandas as pd

In [43]:
samples_df=pd.DataFrame.from_dict(samples)



In [45]:
samples_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   html_url        5 non-null      object
 1   title           5 non-null      object
 2   comments        5 non-null      object
 3   body            5 non-null      object
 4   comment_length  5 non-null      int64 
 5   text            5 non-null      object
 6   embeddings      5 non-null      object
dtypes: int64(1), object(6)
memory usage: 412.0+ bytes


In [46]:
samples_df["scores"]=scores

In [47]:
samples_df.sort_values("scores", ascending=False, inplace=True)

In [48]:
for _, row in samples_df.iterrows():
    print(f"COMMENT: {row.comments}")
    print(f"SCORE: {row.scores}")
    print(f"TITLE: {row.title}")
    print(f"URL: {row.html_url}")
    print("=" * 50)
    print()

COMMENT: Requiring online connection is a deal breaker in some cases unfortunately so it'd be great if offline mode is added similar to how `transformers` loads models offline fine.

@mandubian's second bullet point suggests that there's a workaround allowing you to use your offline (custom?) dataset with `datasets`. Could you please elaborate on how that should look like?
SCORE: 25.505020141601562
TITLE: Discussion using datasets in offline mode
URL: https://github.com/huggingface/datasets/issues/824

COMMENT: The local dataset builders (csv, text , json and pandas) are now part of the `datasets` package since #1726 :)
You can now use them offline
```python
datasets = load_dataset('text', data_files=data_files)
```

We'll do a new release soon
SCORE: 24.55553436279297
TITLE: Discussion using datasets in offline mode
URL: https://github.com/huggingface/datasets/issues/824

COMMENT: I opened a PR that allows to reload modules that have already been loaded once even if there's no interne